name: Deploy frontend

on:
  push:
    branches:
      - deploy/frontend
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@
      with:
        node-version: 12
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: "Install dependencies"
      run: yarn
    - name: "Build webapp"
      run: yarn frontend:build
    - name: "Upload to S3"
      run: aws s3 cp packages/frontend/.build s3://${{ secrets.S3_BUCKET_NAME }}/ --recursive
